theme: jekyll-theme-tactile
title: Karolina's Algorithms Progress Tracker
description: Leetcode questions with my solutions
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Dynamic Programming
    url: DP
  - title: Divide and Conquer
    url: divandconquer
  - title: Cyclic Replacements
    url: cyclic
  - title: Miscellaneous
    url: other
  - title: Arrays
    url: arrays
  - title: Linked Lists
    url: linkedlist
  - title: Binary Trees
    url: binarytree
  - title: Stacks
    url: stack
  
 