theme: jekyll-theme-tactile
title: Karolina's Algorithms Progress Tracker
description: Leetcode questions with my solutions
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Elements of Programming Scenario Three(Term Project)
    url: EOP
 